language: ruby
sudo: required
addons:
  chrome: stable
services: docker
env:
  DOCKER_COMPOSE_VERSION: 1.8.0
before_install:
  - sudo apt-get update -qq
  - gem install bundler
  - bundler install

script:
  - cucumber --version
  - bundler exec cucumber
