language: ruby
sudo: required
services: docker
env:
  DOCKER_COMPOSE_VERSION: 1.8.0
before_install:
  - sudo apt-get update -qq
  - gem install bundler
  - bundler install

before_script:
  - java -jar selenium-server-standalone-3.9.1.jar -role hub
  - java -jar selenium-server-standalone-3.9.1.jar -role node  -hub http://localhost:4444/grid/register

script:
  - cucumber --version
  - bundler exec cucumber
